# Unordered list indentation
MD007:
    indent: 2

MD012: false # allow blank lines

MD013:
    line_length: 800
    tables: false

MD024: false # duplicate headings
MD032: false # blanks-around-lists Lists should be surrounded by blank lines
MD033: false # inline HTML
MD047: false # single-trailing-newline Files should end with a single newline character
