name: respec

# author: @MikeRalphson, @ralfhandl
# issue: https://github.com/OAI/OpenAPI-Specification/issues/1564

#
# This workflow creates a pull request for publishing HTML spec versions to the spec.openapis.org site.
#

# run this manually or on push of new spec versions to main
on:
  push:
    paths:
      - "versions/**"
    branches:
      - main
  workflow_dispatch: {}

jobs:
  respec:
    if: github.repository == 'OAI/Overlay-Specification'

    runs-on: ubuntu-22.04

    steps:
      - name: Generate access token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.OAI_SPEC_PUBLISHER_APPID }}
          private-key: ${{ secrets.OAI_SPEC_PUBLISHER_PRIVATE_KEY }}
          owner: OAI
          repositories: spec.openapis.org

      - uses: actions/checkout@v5 # checkout main branch of this repo
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6 # setup Node.js
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - uses: actions/checkout@v5 # checkout main branch of website repo
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: OAI/spec.openapis.org
          ref: main
          path: deploy

      - name: run main script
        run: scripts/md2html/build.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: overlay-spec-versions
          base: main
          delete-branch: true
          path: deploy
          labels: Overlay,Specification
          reviewers: earth2marsh,lornajane,mikekistler,miqui,baywet,ralfhandl
          title: Overlay - update ReSpec-rendered specification versions
          commit-message: Update ReSpec-rendered specification versions
          signoff: true
          body: |
            This pull request is automatically generated by GitHub action `respec` in the OAI/Overlay-Specification repo.

            The `versions/*.md` files of the OpenAPI Specification have changed and the corresponding HTML files are regenerated.
