name: validate-markdown

# Author: @ralfhandl based on work of @MikeRalphson
# Issue: https://github.com/OAI/Overlay-Specification/issues/53

#
# This workflow validates markdown files in the versions directory matching *.md
#

# run this on pull-requests (creation and updates) and on manual trigger
on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  mdv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5 # checkout repo content
        with:
          fetch-depth: 0
      # - name: use the javascript environment from main
      #   run: |
      #     git checkout remotes/origin/main -- package.json package-lock.json .markdownlint.yaml
      - uses: actions/setup-node@v6 # setup Node.js
        with:
          node-version: "20.x"
      - name: Validate markdown
        run: npx --yes mdv versions/*.md
      - name: Lint markdown
        run: npx --yes markdownlint-cli --config .markdownlint.yaml versions/*.md
